-- AlterTable
ALTER TABLE "ShopListing" ADD COLUMN     "maxCash" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "maxGold" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "maxTotal" INTEGER NOT NULL DEFAULT 3;
